[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "detectorist"
dynamic = ["version"]

description = "A desktop application for sorting and cropping photos using a machine learning for object detection."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "onnxruntime",
    "opencv-python",
    "pillow-heif",
    "pyside6",
    "rawpy",
    "numpy",
    "piexif",
]

[dependency-groups]
dev = [
    "ruff",
    "nuitka",
    "imageio",
    "poethepoet",
    "md-toc",
]

[project.scripts]
detectorist = "detectorist.main:main"

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["detectorist"]

[tool.setuptools.dynamic]
version = {attr = "detectorist._version.__version__"}

[tool.poe.tasks]
compile-ui = { shell = "for f in src/detectorist/*.ui; do pyside6-uic --from-imports \"$f\" -o \"${f%.ui}.py\"; done", help = "Compile Qt UI files to Python files with relative imports" }
compile-qrc = { shell = "export SOURCE_DATE_EPOCH=0 && for f in src/detectorist/*.qrc; do pyside6-rcc \"$f\" -o \"${f%.qrc}_rc.py\"; done", help = "Compile Qt resource files to Python files" }

run-app = { cmd = "uv run src/detectorist/main.py", help = "Run the application" }
run = { sequence = ["compile-ui", "compile-qrc", "run-app"], help = "Compile UI and resource files and run the application" }

get_app_version = { shell = "python -c 'from detectorist._version import __version__; print(__version__.strip())'", help = "Get the application version" }

clean-dist = { shell = "rm -rf ./dist/*", help = "Clean the dist directory" }

ruff = { cmd = "uv run ruff check", help = "Run ruff linter" }

[tool.poe.tasks.build]
help = "Build for the current platform"
shell = """
case "$(uname -s)" in
    Darwin) poe build-mac ;;
    Linux) poe build-linux ;;
    MINGW*|MSYS*|CYGWIN*) poe build-windows ;;
    *) echo "Unsupported OS: $(uname -s)"; exit 1 ;;
esac
"""

[tool.poe.tasks.build-linux]
shell = """
ARCH=$(uname -m)
OUTPUT_DIR=dist/linux-$ARCH
rm -rf "$OUTPUT_DIR"
nuitka \
    --standalone \
    --onefile \
    --enable-plugin=pyside6 \
    --noinclude-qt-translations \
    --noinclude-dlls='*.cpp.o' \
    --noinclude-dlls='*.qsb' \
    --include-qt-plugins=platforminputcontexts \
    --disable-ccache \
    --output-dir="$OUTPUT_DIR" \
    --linux-icon=assets/icon.png \
    --remove-output \
    --output-filename=Detectorist-$(poe get_app_version)-linux-$ARCH \
    ./src/detectorist/main.py
"""
deps = ["compile-ui", "compile-qrc"]
help = "Build the application for Linux"

[tool.poe.tasks.build-mac]
shell = """
ARCH=$(uname -m)
VERSION=$(poe get_app_version)
OUTPUT_DIR=dist/macos-$ARCH
rm -rf "$OUTPUT_DIR"
nuitka \
    --standalone \
    --macos-create-app-bundle \
    --macos-app-icon=assets/icon.png \
    --enable-plugin=pyside6 \
    --noinclude-qt-translations \
    --noinclude-dlls='*.cpp.o' \
    --noinclude-dlls='*.qsb' \
    --include-qt-plugins=platforminputcontexts \
    --disable-ccache \
    --output-dir="$OUTPUT_DIR" \
    --remove-output \
    --product-name=Detectorist \
    --macos-app-name=Detectorist \
    --macos-app-version=$VERSION \
    --macos-signed-app-name=de.ken.detectorist \
    --output-filename=Detectorist-$VERSION-macos-$ARCH \
    ./src/detectorist/main.py
mv  "$OUTPUT_DIR/main.app" \
    "$OUTPUT_DIR/Detectorist-$VERSION-macos-$ARCH.app"
"""
deps = ["compile-ui", "compile-qrc"]
help = "Build the application for macOS"


[tool.poe.tasks.build-windows]
shell = """
ARCH=$(uname -m)
VERSION=$(poe get_app_version)
OUTPUT_DIR=dist/windows-$ARCH
rm -rf "$OUTPUT_DIR"
nuitka.cmd \
    --standalone \
    --onefile \
    --onefile-tempdir-spec={PROGRAM_DIR}/.runtime/{PID}_{TIME} \
    --enable-plugin=pyside6 \
    --windows-icon-from-ico=assets/icon.ico \
    --onefile-windows-splash-screen-image=assets/splash.png \
    --noinclude-qt-translations \
    --noinclude-dlls='*.cpp.o' \
    --noinclude-dlls='*.qsb' \
    --include-qt-plugins=platforminputcontexts \
    --disable-ccache \
    --output-dir="$OUTPUT_DIR" \
    --remove-output \
    --windows-product-name=Detectorist \
    --windows-product-version=$VERSION \
    --windows-file-version=$VERSION \
    --windows-console-mode=attach \
    --output-filename=Detectorist-$VERSION-windows-$ARCH \
    --assume-yes-for-downloads \
    --msvc=latest \
    ./src/detectorist/main.py
"""
deps = ["compile-ui", "compile-qrc"]
help = "Build the application for Windows"


[tool.vscode.tasks]
compile-ui = "poe compile-ui"
compile-qrc = "poe compile-qrc"
run = "poe run-app"
build-and-run = "poe run"

[tool.ruff]
# Exclude designer generated files from .ui
exclude = [
    "src/detectorist/detectorist_app_gui.py",
    "src/detectorist/about_dialog.py",
    "src/detectorist/download_models_dialog.py",
]
[tool.ruff.lint]
# Never enforce `E501` (line length violations).
ignore = ["E501"]
# Select specific error codes to enforce
select = [
    "F",    # Pyflakes (basic Python errors)
    "E",    # pycodestyle errors
    "W",    # pycodestyle warnings
    "I",    # Import sorting
    "C4",   # Flake8 Comprehensions
    "B",    # Flake8 Bugbear (security and design checks)
    "UP",   # Pyupgrade (modernize Python code)
]

[tool.pytest.ini_options]
pythonpath = ["src"]
