[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "detectorist"
dynamic = ["version"]

description = "A desktop application for sorting and cropping photos using a machine learning for object detection."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "onnxruntime",
    "opencv-python",
    "pillow-heif",
    "pyside6",
    "rawpy",
    "numpy",
    "exifread",
]

[dependency-groups]
dev = [
    "ruff",
    "nuitka",
    "imageio",
    "poethepoet",
]

[project.scripts]
detectorist = "detectorist.main:main"

[tool.setuptools]
packages = ["detectorist"]

[tool.setuptools.dynamic]
version = {attr = "detectorist._version.__version__"}

[tool.poe.tasks]
compile-ui = { shell = "for f in detectorist/*.ui; do pyside6-uic \"$f\" -o \"${f%.ui}.py\"; done" }
run-app = "uv run detectorist/main.py"
run = ["compile-ui", "run-app"]

get_app_version = "python -c 'from detectorist._version import __version__; print(__version__.strip())'"

build-mac = { shell = """
nuitka \
    --standalone \
    --macos-create-app-bundle \
    --macos-app-icon=assets/icon.png \
    --enable-plugin=pyside6 \
    --noinclude-qt-translations \
    --noinclude-dlls='*.cpp.o' \
    --noinclude-dlls='*.qsb' \
    --include-qt-plugins=platforminputcontexts \
    --include-data-dir=models=models \
    --disable-ccache \
    --output-dir=dist/macos \
    --remove-output \
    --product-name=Detectorist \
    --macos-app-name=Detectorist \
    --macos-app-version=$(poe get_app_version) \
    --macos-signed-app-name=de.ken.detectorist \
    --output-filename=Detectorist \
    ./detectorist/main.py
mv  dist/macos/main.app \
    dist/macos/Detectorist.app
""" }

build-windows = { shell = """
nuitka.cmd \
    --standalone \
    --onefile \
    --onefile-tempdir-spec={PROGRAM_DIR}/.runtime/{PID}_{TIME} \
    --enable-plugin=pyside6 \
    --windows-icon-from-ico=assets/icon.ico \
    --onefile-windows-splash-screen-image=assets/splash.png \
    --noinclude-qt-translations \
    --noinclude-dlls='*.cpp.o' \
    --noinclude-dlls='*.qsb' \
    --include-qt-plugins=platforminputcontexts \
    --include-data-dir=models=models \
    --disable-ccache \
    --output-dir=dist/windows \
    --remove-output \
    --windows-product-name=Detectorist \
    --windows-product-version=$(poe get_app_version) \
    --windows-file-version=$(poe get_app_version) \
    --windows-console-mode=attach \
    --output-filename=Detectorist \
    --assume-yes-for-downloads \
    ./detectorist/main.py
""" }

build-linux = """
nuitka
    --standalone
    --enable-plugin=pyside6
    --noinclude-qt-translations
    --noinclude-dlls='*.cpp.o'
    --noinclude-dlls='*.qsb'
    --include-qt-plugins=platforminputcontexts
    --include-data-dir=models=models
    --disable-ccache
    --output-dir=dist
    --remove-output
    detectorist/main.py
"""

clean = { shell = "rm -rf dist/*" }


[tool.vscode.tasks]
compile-ui = { shell = "for f in detectorist/*.ui; do pyside6-uic \"$f\" -o \"${f%.ui}.py\"; done" }
run = "python detectorist/main.py"
build-and-run = ["compile-ui", "run"]

[tool.ruff]
# Exclude designer generated files from .ui
exclude = [
    "detectorist/model_viewer_gui.py",
    "detectorist/about_dialog.py",
]
[tool.ruff.lint]
# Never enforce `E501` (line length violations).
ignore = ["E501"]
# Select specific error codes to enforce
select = [
    "F",    # Pyflakes (basic Python errors)
    "E",    # pycodestyle errors
    "W",    # pycodestyle warnings
    "I",    # Import sorting
    "C4",   # Flake8 Comprehensions
    "B",    # Flake8 Bugbear (security and design checks)
    "UP",   # Pyupgrade (modernize Python code)
]