# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'detectorist_app_gui.ui'
##
## Created by: Qt User Interface Compiler version 6.10.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QApplication, QButtonGroup, QCheckBox,
    QComboBox, QGridLayout, QGroupBox, QHBoxLayout,
    QLabel, QListView, QMainWindow, QMenu,
    QMenuBar, QRadioButton, QScrollArea, QSizePolicy,
    QSlider, QSpinBox, QSplitter, QStatusBar,
    QVBoxLayout, QWidget)

class Ui_DetectoristAppUI(object):
    def setupUi(self, DetectoristAppUI):
        if not DetectoristAppUI.objectName():
            DetectoristAppUI.setObjectName(u"DetectoristAppUI")
        DetectoristAppUI.resize(1500, 750)
        self.open_images_action = QAction(DetectoristAppUI)
        self.open_images_action.setObjectName(u"open_images_action")
        self.open_images_action.setShortcutVisibleInContextMenu(True)
        self.open_folder_action = QAction(DetectoristAppUI)
        self.open_folder_action.setObjectName(u"open_folder_action")
        self.open_folder_action.setShortcutVisibleInContextMenu(True)
        self.crop_and_export_selected_images_action = QAction(DetectoristAppUI)
        self.crop_and_export_selected_images_action.setObjectName(u"crop_and_export_selected_images_action")
        self.crop_and_export_selected_images_action.setEnabled(False)
        self.crop_and_export_selected_images_action.setShortcutVisibleInContextMenu(True)
        self.crop_and_export_all_images_action = QAction(DetectoristAppUI)
        self.crop_and_export_all_images_action.setObjectName(u"crop_and_export_all_images_action")
        self.crop_and_export_all_images_action.setEnabled(False)
        self.crop_and_export_all_images_action.setShortcutVisibleInContextMenu(True)
        self.about_action = QAction(DetectoristAppUI)
        self.about_action.setObjectName(u"about_action")
        self.about_action.setShortcutVisibleInContextMenu(True)
        self.group_images_by_object_class_action = QAction(DetectoristAppUI)
        self.group_images_by_object_class_action.setObjectName(u"group_images_by_object_class_action")
        self.group_images_by_object_class_action.setEnabled(False)
        self.group_images_by_object_class_action.setShortcutVisibleInContextMenu(True)
        self.clear_image_list_action = QAction(DetectoristAppUI)
        self.clear_image_list_action.setObjectName(u"clear_image_list_action")
        self.clear_image_list_action.setEnabled(False)
        self.clear_image_list_action.setShortcutVisibleInContextMenu(True)
        self.remove_selected_images_from_list_action = QAction(DetectoristAppUI)
        self.remove_selected_images_from_list_action.setObjectName(u"remove_selected_images_from_list_action")
        self.remove_selected_images_from_list_action.setEnabled(False)
        self.remove_selected_images_from_list_action.setShortcutVisibleInContextMenu(True)
        self.locate_image_in_filemanager_action = QAction(DetectoristAppUI)
        self.locate_image_in_filemanager_action.setObjectName(u"locate_image_in_filemanager_action")
        self.locate_image_in_filemanager_action.setEnabled(False)
        self.locate_image_in_filemanager_action.setShortcutVisibleInContextMenu(True)
        self.copy_filenames_to_clipboard_action = QAction(DetectoristAppUI)
        self.copy_filenames_to_clipboard_action.setObjectName(u"copy_filenames_to_clipboard_action")
        self.copy_filenames_to_clipboard_action.setEnabled(False)
        self.copy_filenames_to_clipboard_action.setShortcutVisibleInContextMenu(True)
        self.copy_export_remove_action = QAction(DetectoristAppUI)
        self.copy_export_remove_action.setObjectName(u"copy_export_remove_action")
        self.copy_export_remove_action.setEnabled(False)
        self.copy_export_remove_action.setShortcutVisibleInContextMenu(True)
        self.central_widget = QWidget(DetectoristAppUI)
        self.central_widget.setObjectName(u"central_widget")
        self.main_layout = QHBoxLayout(self.central_widget)
        self.main_layout.setObjectName(u"main_layout")
        self.splitter = QSplitter(self.central_widget)
        self.splitter.setObjectName(u"splitter")
        self.splitter.setOrientation(Qt.Orientation.Horizontal)
        self.image_list_view = QListView(self.splitter)
        self.image_list_view.setObjectName(u"image_list_view")
        self.image_list_view.setEditTriggers(QAbstractItemView.EditTrigger.NoEditTriggers)
        self.image_list_view.setSelectionMode(QAbstractItemView.SelectionMode.ExtendedSelection)
        self.splitter.addWidget(self.image_list_view)
        self.image_label = QLabel(self.splitter)
        self.image_label.setObjectName(u"image_label")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image_label.sizePolicy().hasHeightForWidth())
        self.image_label.setSizePolicy(sizePolicy)
        self.image_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.splitter.addWidget(self.image_label)
        self.right_side_widget = QWidget(self.splitter)
        self.right_side_widget.setObjectName(u"right_side_widget")
        self.verticalLayout = QVBoxLayout(self.right_side_widget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.model_group_box = QGroupBox(self.right_side_widget)
        self.model_group_box.setObjectName(u"model_group_box")
        self.model_group_box.setEnabled(True)
        self.gridLayout_2 = QGridLayout(self.model_group_box)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.model_select_combo_box = QComboBox(self.model_group_box)
        self.model_select_combo_box.setObjectName(u"model_select_combo_box")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.model_select_combo_box.sizePolicy().hasHeightForWidth())
        self.model_select_combo_box.setSizePolicy(sizePolicy1)

        self.gridLayout_2.addWidget(self.model_select_combo_box, 0, 0, 1, 3)

        self.confidence_label = QLabel(self.model_group_box)
        self.confidence_label.setObjectName(u"confidence_label")

        self.gridLayout_2.addWidget(self.confidence_label, 1, 0, 1, 1)

        self.confidence_slider = QSlider(self.model_group_box)
        self.confidence_slider.setObjectName(u"confidence_slider")
        self.confidence_slider.setEnabled(True)
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.MinimumExpanding, QSizePolicy.Policy.Fixed)
        sizePolicy2.setHorizontalStretch(1)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.confidence_slider.sizePolicy().hasHeightForWidth())
        self.confidence_slider.setSizePolicy(sizePolicy2)
        self.confidence_slider.setMinimum(1)
        self.confidence_slider.setMaximum(100)
        self.confidence_slider.setSingleStep(10)
        self.confidence_slider.setSliderPosition(75)
        self.confidence_slider.setOrientation(Qt.Orientation.Horizontal)
        self.confidence_slider.setTickPosition(QSlider.TickPosition.NoTicks)

        self.gridLayout_2.addWidget(self.confidence_slider, 1, 1, 1, 1)

        self.confidence_spin_box = QSpinBox(self.model_group_box)
        self.confidence_spin_box.setObjectName(u"confidence_spin_box")
        self.confidence_spin_box.setMinimum(1)
        self.confidence_spin_box.setMaximum(100)
        self.confidence_spin_box.setValue(75)

        self.gridLayout_2.addWidget(self.confidence_spin_box, 1, 2, 1, 1)


        self.verticalLayout.addWidget(self.model_group_box)

        self.detection_info_group_box = QGroupBox(self.right_side_widget)
        self.detection_info_group_box.setObjectName(u"detection_info_group_box")
        self.verticalLayout_4 = QVBoxLayout(self.detection_info_group_box)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.detection_info_label = QLabel(self.detection_info_group_box)
        self.detection_info_label.setObjectName(u"detection_info_label")

        self.verticalLayout_4.addWidget(self.detection_info_label)


        self.verticalLayout.addWidget(self.detection_info_group_box)

        self.crop_info_group_box = QGroupBox(self.right_side_widget)
        self.crop_info_group_box.setObjectName(u"crop_info_group_box")
        self.grdlyt_crop = QGridLayout(self.crop_info_group_box)
        self.grdlyt_crop.setObjectName(u"grdlyt_crop")
        self.rb_crop_all_detected_objects = QRadioButton(self.crop_info_group_box)
        self.btngroup_crop = QButtonGroup(DetectoristAppUI)
        self.btngroup_crop.setObjectName(u"btngroup_crop")
        self.btngroup_crop.addButton(self.rb_crop_all_detected_objects)
        self.rb_crop_all_detected_objects.setObjectName(u"rb_crop_all_detected_objects")
        self.rb_crop_all_detected_objects.setChecked(True)

        self.grdlyt_crop.addWidget(self.rb_crop_all_detected_objects, 0, 0, 1, 2)

        self.rb_crop_to_top_conf = QRadioButton(self.crop_info_group_box)
        self.btngroup_crop.addButton(self.rb_crop_to_top_conf)
        self.rb_crop_to_top_conf.setObjectName(u"rb_crop_to_top_conf")
        self.rb_crop_to_top_conf.setChecked(False)

        self.grdlyt_crop.addWidget(self.rb_crop_to_top_conf, 1, 0, 1, 2)

        self.rb_crop_centered_obj = QRadioButton(self.crop_info_group_box)
        self.btngroup_crop.addButton(self.rb_crop_centered_obj)
        self.rb_crop_centered_obj.setObjectName(u"rb_crop_centered_obj")
        self.rb_crop_centered_obj.setChecked(False)

        self.grdlyt_crop.addWidget(self.rb_crop_centered_obj, 2, 0, 1, 2)

        self.rb_crop_largest_area = QRadioButton(self.crop_info_group_box)
        self.btngroup_crop.addButton(self.rb_crop_largest_area)
        self.rb_crop_largest_area.setObjectName(u"rb_crop_largest_area")
        self.rb_crop_largest_area.setChecked(False)

        self.grdlyt_crop.addWidget(self.rb_crop_largest_area, 3, 0, 1, 2)

        self.crop_ratio_combo_box = QComboBox(self.crop_info_group_box)
        self.crop_ratio_combo_box.addItem("")
        self.crop_ratio_combo_box.addItem("")
        self.crop_ratio_combo_box.addItem("")
        self.crop_ratio_combo_box.addItem("")
        self.crop_ratio_combo_box.addItem("")
        self.crop_ratio_combo_box.addItem("")
        self.crop_ratio_combo_box.addItem("")
        self.crop_ratio_combo_box.addItem("")
        self.crop_ratio_combo_box.addItem("")
        self.crop_ratio_combo_box.addItem("")
        self.crop_ratio_combo_box.addItem("")
        self.crop_ratio_combo_box.addItem("")
        self.crop_ratio_combo_box.addItem("")
        self.crop_ratio_combo_box.setObjectName(u"crop_ratio_combo_box")

        self.grdlyt_crop.addWidget(self.crop_ratio_combo_box, 4, 0, 1, 3)

        self.padding_label = QLabel(self.crop_info_group_box)
        self.padding_label.setObjectName(u"padding_label")

        self.grdlyt_crop.addWidget(self.padding_label, 5, 0, 1, 1)

        self.padding_slider = QSlider(self.crop_info_group_box)
        self.padding_slider.setObjectName(u"padding_slider")
        self.padding_slider.setEnabled(True)
        sizePolicy2.setHeightForWidth(self.padding_slider.sizePolicy().hasHeightForWidth())
        self.padding_slider.setSizePolicy(sizePolicy2)
        self.padding_slider.setMaximum(50)
        self.padding_slider.setSingleStep(1)
        self.padding_slider.setSliderPosition(15)
        self.padding_slider.setOrientation(Qt.Orientation.Horizontal)
        self.padding_slider.setTickPosition(QSlider.TickPosition.NoTicks)

        self.grdlyt_crop.addWidget(self.padding_slider, 5, 1, 1, 1)

        self.padding_spin_box = QSpinBox(self.crop_info_group_box)
        self.padding_spin_box.setObjectName(u"padding_spin_box")
        self.padding_spin_box.setMaximum(50)
        self.padding_spin_box.setValue(15)

        self.grdlyt_crop.addWidget(self.padding_spin_box, 5, 2, 1, 1)

        self.cb_comp_cam_exposure = QCheckBox(self.crop_info_group_box)
        self.cb_comp_cam_exposure.setObjectName(u"cb_comp_cam_exposure")
        self.cb_comp_cam_exposure.setChecked(True)

        self.grdlyt_crop.addWidget(self.cb_comp_cam_exposure, 6, 0, 1, 3)


        self.verticalLayout.addWidget(self.crop_info_group_box)

        self.image_info_group_box = QGroupBox(self.right_side_widget)
        self.image_info_group_box.setObjectName(u"image_info_group_box")
        self.verticalLayout_3 = QVBoxLayout(self.image_info_group_box)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.image_info_label = QLabel(self.image_info_group_box)
        self.image_info_label.setObjectName(u"image_info_label")

        self.verticalLayout_3.addWidget(self.image_info_label)


        self.verticalLayout.addWidget(self.image_info_group_box)

        self.image_exif_group_box = QGroupBox(self.right_side_widget)
        self.image_exif_group_box.setObjectName(u"image_exif_group_box")
        self.horizontalLayout = QHBoxLayout(self.image_exif_group_box)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.scrollArea = QScrollArea(self.image_exif_group_box)
        self.scrollArea.setObjectName(u"scrollArea")
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 298, 114))
        self.horizontalLayout_2 = QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.image_exif_label = QLabel(self.scrollAreaWidgetContents)
        self.image_exif_label.setObjectName(u"image_exif_label")
        self.image_exif_label.setTextInteractionFlags(Qt.TextInteractionFlag.LinksAccessibleByMouse|Qt.TextInteractionFlag.TextSelectableByMouse)

        self.horizontalLayout_2.addWidget(self.image_exif_label, 0, Qt.AlignmentFlag.AlignTop)

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.horizontalLayout.addWidget(self.scrollArea)


        self.verticalLayout.addWidget(self.image_exif_group_box)

        self.splitter.addWidget(self.right_side_widget)

        self.main_layout.addWidget(self.splitter)

        DetectoristAppUI.setCentralWidget(self.central_widget)
        self.menu_bar = QMenuBar(DetectoristAppUI)
        self.menu_bar.setObjectName(u"menu_bar")
        self.menu_bar.setGeometry(QRect(0, 0, 1500, 30))
        self.menu_file = QMenu(self.menu_bar)
        self.menu_file.setObjectName(u"menu_file")
        self.menu_actions = QMenu(self.menu_bar)
        self.menu_actions.setObjectName(u"menu_actions")
        self.menu_help = QMenu(self.menu_bar)
        self.menu_help.setObjectName(u"menu_help")
        DetectoristAppUI.setMenuBar(self.menu_bar)
        self.status_bar = QStatusBar(DetectoristAppUI)
        self.status_bar.setObjectName(u"status_bar")
        DetectoristAppUI.setStatusBar(self.status_bar)

        self.menu_bar.addAction(self.menu_file.menuAction())
        self.menu_bar.addAction(self.menu_actions.menuAction())
        self.menu_bar.addAction(self.menu_help.menuAction())
        self.menu_file.addAction(self.open_images_action)
        self.menu_file.addAction(self.open_folder_action)
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.clear_image_list_action)
        self.menu_actions.addAction(self.group_images_by_object_class_action)
        self.menu_actions.addSeparator()
        self.menu_actions.addAction(self.crop_and_export_all_images_action)
        self.menu_actions.addAction(self.crop_and_export_selected_images_action)
        self.menu_actions.addSeparator()
        self.menu_help.addAction(self.about_action)

        self.retranslateUi(DetectoristAppUI)
        self.confidence_spin_box.valueChanged.connect(self.confidence_slider.setValue)
        self.confidence_slider.valueChanged.connect(self.confidence_spin_box.setValue)
        self.padding_slider.valueChanged.connect(self.padding_spin_box.setValue)
        self.padding_spin_box.valueChanged.connect(self.padding_slider.setValue)

        QMetaObject.connectSlotsByName(DetectoristAppUI)
    # setupUi

    def retranslateUi(self, DetectoristAppUI):
        DetectoristAppUI.setWindowTitle(QCoreApplication.translate("DetectoristAppUI", u"Detectorist", None))
        self.open_images_action.setText(QCoreApplication.translate("DetectoristAppUI", u"Open Image(s)...", None))
#if QT_CONFIG(shortcut)
        self.open_images_action.setShortcut(QCoreApplication.translate("DetectoristAppUI", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.open_folder_action.setText(QCoreApplication.translate("DetectoristAppUI", u"Open Folder...", None))
#if QT_CONFIG(shortcut)
        self.open_folder_action.setShortcut(QCoreApplication.translate("DetectoristAppUI", u"Ctrl+Shift+O", None))
#endif // QT_CONFIG(shortcut)
        self.crop_and_export_selected_images_action.setText(QCoreApplication.translate("DetectoristAppUI", u"Crop && Export selected Images", None))
#if QT_CONFIG(shortcut)
        self.crop_and_export_selected_images_action.setShortcut(QCoreApplication.translate("DetectoristAppUI", u"Ctrl+E", None))
#endif // QT_CONFIG(shortcut)
        self.crop_and_export_all_images_action.setText(QCoreApplication.translate("DetectoristAppUI", u"Crop && Export all Images", None))
#if QT_CONFIG(shortcut)
        self.crop_and_export_all_images_action.setShortcut(QCoreApplication.translate("DetectoristAppUI", u"Ctrl+Shift+E", None))
#endif // QT_CONFIG(shortcut)
        self.about_action.setText(QCoreApplication.translate("DetectoristAppUI", u"About", None))
        self.group_images_by_object_class_action.setText(QCoreApplication.translate("DetectoristAppUI", u"Group Images into Folders (by Object Class)", None))
#if QT_CONFIG(shortcut)
        self.group_images_by_object_class_action.setShortcut(QCoreApplication.translate("DetectoristAppUI", u"Ctrl+Shift+G", None))
#endif // QT_CONFIG(shortcut)
        self.clear_image_list_action.setText(QCoreApplication.translate("DetectoristAppUI", u"Clear Image List", None))
#if QT_CONFIG(shortcut)
        self.clear_image_list_action.setShortcut(QCoreApplication.translate("DetectoristAppUI", u"Ctrl+Backspace", None))
#endif // QT_CONFIG(shortcut)
        self.remove_selected_images_from_list_action.setText(QCoreApplication.translate("DetectoristAppUI", u"Remove selected Images from List", None))
#if QT_CONFIG(tooltip)
        self.remove_selected_images_from_list_action.setToolTip(QCoreApplication.translate("DetectoristAppUI", u"Removes the selected Image(s) from the List. The images are not deleted, just removed from the view", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.remove_selected_images_from_list_action.setShortcut(QCoreApplication.translate("DetectoristAppUI", u"Backspace", None))
#endif // QT_CONFIG(shortcut)
        self.locate_image_in_filemanager_action.setText(QCoreApplication.translate("DetectoristAppUI", u"Locate Image in Filemanager", None))
#if QT_CONFIG(tooltip)
        self.locate_image_in_filemanager_action.setToolTip(QCoreApplication.translate("DetectoristAppUI", u"Locate Image in Filemanager", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.locate_image_in_filemanager_action.setShortcut(QCoreApplication.translate("DetectoristAppUI", u"Ctrl+L", None))
#endif // QT_CONFIG(shortcut)
        self.copy_filenames_to_clipboard_action.setText(QCoreApplication.translate("DetectoristAppUI", u"Copy Filenames to Clipboard", None))
#if QT_CONFIG(tooltip)
        self.copy_filenames_to_clipboard_action.setToolTip(QCoreApplication.translate("DetectoristAppUI", u"Copy Filenames to Clipboard", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.copy_filenames_to_clipboard_action.setShortcut(QCoreApplication.translate("DetectoristAppUI", u"Ctrl+C", None))
#endif // QT_CONFIG(shortcut)
        self.copy_export_remove_action.setText(QCoreApplication.translate("DetectoristAppUI", u"Crop && Export && Remove selected Images from List ", None))
#if QT_CONFIG(tooltip)
        self.copy_export_remove_action.setToolTip(QCoreApplication.translate("DetectoristAppUI", u"Starts a batch process that crops and exports the selected image(s) into a subfolder and also removes the image(s) from the list", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.copy_export_remove_action.setShortcut(QCoreApplication.translate("DetectoristAppUI", u"Alt+E", None))
#endif // QT_CONFIG(shortcut)
        self.image_label.setStyleSheet(QCoreApplication.translate("DetectoristAppUI", u"background-color: gray;", None))
        self.image_label.setText(QCoreApplication.translate("DetectoristAppUI", u"Open Folder...", None))
        self.model_group_box.setTitle(QCoreApplication.translate("DetectoristAppUI", u"Model", None))
#if QT_CONFIG(tooltip)
        self.model_select_combo_box.setToolTip(QCoreApplication.translate("DetectoristAppUI", u"Model used for object detection", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.confidence_label.setToolTip(QCoreApplication.translate("DetectoristAppUI", u"The confidence threshold for filtering detections", None))
#endif // QT_CONFIG(tooltip)
        self.confidence_label.setText(QCoreApplication.translate("DetectoristAppUI", u"Confidence", None))
#if QT_CONFIG(tooltip)
        self.confidence_slider.setToolTip(QCoreApplication.translate("DetectoristAppUI", u"The confidence threshold for filtering detections", None))
#endif // QT_CONFIG(tooltip)
        self.detection_info_group_box.setTitle(QCoreApplication.translate("DetectoristAppUI", u"Detection", None))
        self.detection_info_label.setText(QCoreApplication.translate("DetectoristAppUI", u"Objects			: -\n"
"Detection time		: -\n"
"Highest confidence	: -", None))
        self.crop_info_group_box.setTitle(QCoreApplication.translate("DetectoristAppUI", u"Crop", None))
#if QT_CONFIG(tooltip)
        self.rb_crop_all_detected_objects.setToolTip(QCoreApplication.translate("DetectoristAppUI", u"Crops all detected objects into individual images", None))
#endif // QT_CONFIG(tooltip)
        self.rb_crop_all_detected_objects.setText(QCoreApplication.translate("DetectoristAppUI", u"Crop all detected objects individually", None))
#if QT_CONFIG(tooltip)
        self.rb_crop_to_top_conf.setToolTip(QCoreApplication.translate("DetectoristAppUI", u"Crops to the object with the highest confidence only into a new image", None))
#endif // QT_CONFIG(tooltip)
        self.rb_crop_to_top_conf.setText(QCoreApplication.translate("DetectoristAppUI", u"Crop to object with highest confidence", None))
#if QT_CONFIG(tooltip)
        self.rb_crop_centered_obj.setToolTip(QCoreApplication.translate("DetectoristAppUI", u"Crops to the most centrally located of all detected objects only into a new image", None))
#endif // QT_CONFIG(tooltip)
        self.rb_crop_centered_obj.setText(QCoreApplication.translate("DetectoristAppUI", u"Crop to object closest to center", None))
#if QT_CONFIG(tooltip)
        self.rb_crop_largest_area.setToolTip(QCoreApplication.translate("DetectoristAppUI", u"Crops all detected objects into a single image", None))
#endif // QT_CONFIG(tooltip)
        self.rb_crop_largest_area.setText(QCoreApplication.translate("DetectoristAppUI", u"Crop to largest area", None))
        self.crop_ratio_combo_box.setItemText(0, QCoreApplication.translate("DetectoristAppUI", u"aspect ratio: same as source image", None))
        self.crop_ratio_combo_box.setItemText(1, QCoreApplication.translate("DetectoristAppUI", u"aspect ratio: same as detection frame", None))
        self.crop_ratio_combo_box.setItemText(2, QCoreApplication.translate("DetectoristAppUI", u"3:2 (landscape)", None))
        self.crop_ratio_combo_box.setItemText(3, QCoreApplication.translate("DetectoristAppUI", u"4:3  (landscape)", None))
        self.crop_ratio_combo_box.setItemText(4, QCoreApplication.translate("DetectoristAppUI", u"5:4 (landscape)", None))
        self.crop_ratio_combo_box.setItemText(5, QCoreApplication.translate("DetectoristAppUI", u"16:9  (landscape)", None))
        self.crop_ratio_combo_box.setItemText(6, QCoreApplication.translate("DetectoristAppUI", u"21:9 (landscape)", None))
        self.crop_ratio_combo_box.setItemText(7, QCoreApplication.translate("DetectoristAppUI", u"1:1", None))
        self.crop_ratio_combo_box.setItemText(8, QCoreApplication.translate("DetectoristAppUI", u"2:3 (portrait)", None))
        self.crop_ratio_combo_box.setItemText(9, QCoreApplication.translate("DetectoristAppUI", u"3:4 (portrait)", None))
        self.crop_ratio_combo_box.setItemText(10, QCoreApplication.translate("DetectoristAppUI", u"4:5 (portrait)", None))
        self.crop_ratio_combo_box.setItemText(11, QCoreApplication.translate("DetectoristAppUI", u"9:16 (portrait)", None))
        self.crop_ratio_combo_box.setItemText(12, QCoreApplication.translate("DetectoristAppUI", u"9:21 (portrait)", None))

#if QT_CONFIG(tooltip)
        self.crop_ratio_combo_box.setToolTip(QCoreApplication.translate("DetectoristAppUI", u"Aspect ratio for the crop", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.padding_label.setToolTip(QCoreApplication.translate("DetectoristAppUI", u"Adjusts the padding around detected objects as a percentage of the detection bounding box's width/height", None))
#endif // QT_CONFIG(tooltip)
        self.padding_label.setText(QCoreApplication.translate("DetectoristAppUI", u"Padding", None))
#if QT_CONFIG(tooltip)
        self.padding_slider.setToolTip(QCoreApplication.translate("DetectoristAppUI", u"Adjusts the padding around detected objects as a percentage of the detection bounding box's width/height", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.cb_comp_cam_exposure.setToolTip(QCoreApplication.translate("DetectoristAppUI", u"Adjust the EV to correct for any exposure bias based on EXIF data", None))
#endif // QT_CONFIG(tooltip)
        self.cb_comp_cam_exposure.setText(QCoreApplication.translate("DetectoristAppUI", u"Auto correct camera exposure bias", None))
        self.image_info_group_box.setTitle(QCoreApplication.translate("DetectoristAppUI", u"Image", None))
        self.image_info_label.setText(QCoreApplication.translate("DetectoristAppUI", u"-", None))
        self.image_exif_group_box.setTitle(QCoreApplication.translate("DetectoristAppUI", u"Exif", None))
        self.menu_file.setTitle(QCoreApplication.translate("DetectoristAppUI", u"File", None))
        self.menu_actions.setTitle(QCoreApplication.translate("DetectoristAppUI", u"Actions", None))
        self.menu_help.setTitle(QCoreApplication.translate("DetectoristAppUI", u"Help", None))
    # retranslateUi

