name: Build Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [published]

jobs:
  build-macos:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "0.8.9"
        
    - name: Install dependencies
      run: |
        uv venv
        uv pip install -e '.[dev]'
    
    - name: Build macOS app
      run: |
        source .venv/bin/activate
        poe build-mac

    
    - name: Rename macOS app
      run: |
        mv dist/macos/main.app dist/modelviewer.app

    - name: Upload macOS artifact
      uses: actions/upload-artifact@v4
      with:
        name: macos-app
        path: dist/modelviewer.app




  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "0.8.9"

    - name: Install dependencies
      run: |
        uv venv
        uv pip install -e '.[dev]'
        
    - name: Build Windows executable 
      run: |
        .\.venv\Scripts\activate
        poe build-windows
        
    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-exe
        path: dist/modelviewer.dist

  create-release:
    needs: [build-macos, build-windows]
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    
    steps:
    - uses: actions/download-artifact@v4
    
    - name: Compress artifacts
      run: |
        zip -r macos-app.zip macos-app
        zip -r windows-exe.zip windows-exe
        
    - name: Upload Release Assets
      uses: softprops/action-gh-release@v1
      with:
        files: |
          macos-app.zip
          windows-exe.zip